# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Péter Balázs Polgár, Product Design Leader"
title_separator: "|"
name: "Péter Balázs Polgár"
url: "https://polgarp.com"
email: hello@polgarp.com
description: >- # this means to ignore newlines until "baseurl:"
  "Design explorer."
twitter_username: polgarp
github_username: polgarp
minimal_mistakes_skin: "contrast"
search: true
search_full_content: true
site.description: "Ideas and Stuff by Péter Balázs Polgár, Product Design Leader"
logo: "/assets/images/logo.png"
masthead_title: "Péter Balázs Polgár"

# Comments

repository: polgarp/polgarp.github.io

comments:
  provider: "giscus"
  giscus:
    repo_id              : MDEwOlJlcG9zaXRvcnkyNjMxNTQ0ODI= # Shown during giscus setup at https://giscus.app
    category_name        : General # Full text name of the category
    category_id          : DIC_kwDOD69rMs4CYXfz # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
   


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 50 # amount of posts to show
paginate_path: /page:num/
date_format: "%Y. %B %d"
timezone: Europe/Copenhagen

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Péter Balázs Polgár"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : '<i class="fas fa-drafting-compass"></i> Design explorer. <br>Building products <br>and product design teams.'
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/peterbalazspolgar"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mastodon.online/@polgarp"
    - label: "Drop me an email"
      icon: "fas fa-solid fa-envelope"
      url: "mailto:hello@polgarp.com"
    - label: "My newsletter"
      icon: "fas fa-magic"
      url: "https://polgarp.com/categories/newsletter/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin" 
      url: "https://linkedin.com/in/peterbalazspolgar"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mastodon.online/@polgarp"
    - label: "Drop me an email"
      icon: "fas fa-solid fa-envelope"
      url: "mailto:hello@polgarp.com"
    - label: "My newsletter"
      icon: "fas fa-magic"
      url: "https://polgarp.com/categories/newsletter/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

social:
  type: "Person"
  name:  "Péter Balázs Polgár"
  links:
    - "https://twitter.com/polgarp"
    - "https://linkedin.com/in/peterbalazspolgar"

twitter:
  username: "polgarp"
